export const testGeneratingParams = 
     [
        {
            title: "Fog", 
            defaultValue:"",
            getAriaValueText:"",
            step:1,
            min:1,
            max:10,
            marks:"",
            disabeld:"",
        }, 
        {
            title: "Wind", 
            defaultValue:"",
            getAriaValueText:"",
            step:1,
            min:1,
            max:5,
            marks:"",
            disabeld:"",
        },
        {
            title: "Density", 
            defaultValue:"",
            getAriaValueText:"",
            step:1,
            min:1,
            max:5,
            marks:"",
            disabeld:"",
        },
        {
            title: "Brightness", 
            defaultValue:"",
            getAriaValueText:"",
            step:1,
            min:1,
            max:5,
            marks:"",
            disabeld:"",
        },
        {
            title: "Cloudiness", 
            defaultValue:"",
            getAriaValueText:"",
            step:1,
            min:1,
            max:5,
            marks:"",
            disabeld:"",
        },
        {
            title: "Height", 
            defaultValue:"",
            getAriaValueText:"",
            step:1,
            min:1,
            max:5,
            marks:"",
            disabeld:"",
        },
    ]


export const testGeneratingConditions = 
     [
        {
            title: "Time to finish", 
            defaultValue:"",
            getAriaValueText:"",
            step:10,
            min:10,
            max:60,
            marks:"",
            disabeld:"",
        }, 
        {
            title: "Wind", 
            defaultValue:"",
            getAriaValueText:"",
            step:1,
            min:1,
            max:5,
            marks:"",
            disabeld:"",
        },
        {
            title: "Fog", 
            defaultValue:"",
            getAriaValueText:"",
            step:1,
            min:1,
            max:10,
            marks:"",
            disabeld:"",
        },
        {
            title: "Brightness", 
            defaultValue:"",
            getAriaValueText:"",
            step:1,
            min:1,
            max:5,
            marks:"",
            disabeld:"",
        },
    ]
