import drone14 from "../../assets/drone14.png";
import drone15 from "../../assets/drone15.png";
import drone16 from  "../../assets/drone16.png";
import drone17 from "../../assets/drone17.png";
import drone18 from "../../assets/drone18.png";
import drone19 from "../../assets/drone19.png";
import drone20 from "../../assets/drone20.png";
import drone21 from "../../assets/drone21.png";

export const droneData = [
    {
        id: 1, 
        name: "DJI Flycart 30",
        img: drone18, 
        manufactor: "DJI", 
        country: "China",
        model: "As23EE",
        series:"",
        type:"deliveryDrone",
        flight: 50, 
        weight: 3000, 
        camera: "???", 
        specialFeatures:["30 kg Max Payload", "12 m/s Max Wind Speed Resistance", "20 km Video Transmission with O3"],  
    },
    {
        id: 2, 
        name: "DJI Mini 4 Pro",
        img:drone16, 
        manufactor: "DJI", 
        country: "China",
        model: "As23EE",
        series:"Mini",
        type:"cameraDrone",
        flight: 40, 
        weight: 250, 
        camera: "1″ CMOS Primary Camera", 
        specialFeatures:[" 20km FHD Video Transmission", "ActiveTrack 360°", "4K/60fps HDR True Vertical Shooting"], 
    },
    {
        id: 3,
        name: "DJI Air 3S", 
        img:drone15, 
        manufactor: "DJI",
        country: "China", 
        model: "As23EE",
        series:"Air",
        type:"cameraDrone",
        flight: 45, 
        weight: 300, 
        camera: "1″ CMOS Primary Camera", 
        specialFeatures:["Dual-Camera 4K/60fps HDR Video & 14 Stops of Dynamic Range", "Free Panorama, Seamless and Detailed", "20km Video Transmission"], 
    },
    {
        id: 4, 
        name: "DJI Mavic 3 Pro",
        img: drone14, 
        manufactor: "DJI",
        country: "China", 
        model: "As23EE",
        series:"Mavic",
        type:"cameraDrone",
        flight:  43, 
        weight: 300, 
        camera: "4/3 CMOS Hasselblad Camera", 
        specialFeatures:["15km HD Video Transmission", "Omnidirectional Obstacle Sensing", "Cine Only Tri-Camera Apple ProRes Support"], 
    },
    {
        id: 5,
        name: "DJI Neo", 
        img: drone17, 
        manufactor: "DJI",
        country: "China", 
        model: "As23EE",
        series:"Neo",
        type:"cameraDrone",
        flight: 55, 
        weight: 140, 
        camera: "", 
        specialFeatures:["4K Ultra-Stabilized Video", "Palm Takeoff & Landing", "Full-Coverage Propeller Guards"], 
    },
    {
        id: 6, 
        name: "Q4i UAV",
        img: drone19, 
        manufactor: "IdeaForge",
        country: "India", 
        model: "As23EE",
        series:"",
        type:"securityDrone",
        flight: 40, 
        weight: 300, 
        camera: "10X HD Loss-Less Optical Zoom", 
        specialFeatures:["Intelligent autopilot", "Take-off Area Check feature", "Custom Maps Integration"], 
    },
    {
        id: 7, 
        name: "SAMS",
        img:drone20, 
        manufactor: "Height Technologies",
        country: "Nederland",
        model: "SAMS-A",
        series:"",
        type:"securityDrone",
        flight: 55, 
        weight: 900, 
        camera: "", 
        specialFeatures:["Multy functonal applications", "affordable infrastructure", "Stationary or mobile"], 
    },
    {
        id: 8, 
        name: "M300",
        img: drone21, 
        manufactor: "AirVis", 
        country: "UK",
        model: "As23EE",
        series:"",
        type:"securityDrone",
        flight: 50, 
        weight: 1000, 
        camera: "23x hybrid optical zoom", 
        specialFeatures:["Encrypted Radio Link", "​Local Data Mode", "​Airsense System", "Secure Data"], 
    },
    {
        id: 9, 
        name: "DJI Mini 4 Pro copy",
        img:drone16, 
        manufactor: "DJI", 
        country: "China",
        model: "As23EE",
        series:"Mini",
        type:"cameraDrone",
        flight: 40, 
        weight: 250, 
        camera: "1″ CMOS Primary Camera", 
        specialFeatures:[" 20km FHD Video Transmission", "ActiveTrack 360°", "4K/60fps HDR True Vertical Shooting"],
    },
    {
        id: 10,
        name: "DJI Flycart 30 copy",
        img: drone18, 
        manufactor: "DJI", 
        country: "China",
        model: "As23EE",
        series:"",
        type:"deliveryDrone",
        flight: 50, 
        weight: 3000, 
        camera: "???", 
        specialFeatures:[" 20km FHD Video Transmission", "ActiveTrack 360°", "4K/60fps HDR True Vertical Shooting"],
    }
]